MCS2LM-#5 - Support whitespaced file inspection.

diff --git a/scripts/githooks/precommit/pre-commit b/scripts/githooks/precommit/pre-commit
--- a/scripts/githooks/precommit/pre-commit
+++ b/scripts/githooks/precommit/pre-commit
@@ -7,24 +7,33 @@ if [[ -z $files ]]; then
     exit 0
 fi
 
-set -e
-
-for file in "$files"; do
-    file=${file#' '}
-    filesAbsPath="$root/${file} $filesAbsPath"
-done
-
-filesAbsPath=${filesAbsPath%' '}
-golint --set_exit_status "$filesAbsPath"
-go vet "$filesAbsPath"
-unformattedFiles=$(gofmt -l "$filesAbsPath")
 _set_fmt_error_code() {
-    if [[ -n $unformattedFiles ]]; then
-        echo -e "${yellow_bg}${black_txt}${bold}The following files are not properly formatted."
-        echo -e "Run 'go fmt'${reset}"
+    if [[ -n $1 ]]; then
+        echo -e "${yellow_bg}${black_txt}${bold}Format error:${reset} $1"
         return 1
     fi
 }
-_set_fmt_error_code
 
-set +e
+_check_error_code() {
+    if [[ $1 != 0 ]]; then
+      error=1
+      printf "\n"
+    fi
+}
+
+error=0
+files=$(sed 's#^\s#''#g' <<< $files)
+while read file; do
+    abs="$root/$file"
+    golint --set_exit_status "$abs"
+    _check_error_code $?
+
+    go vet "$abs"
+    _check_error_code $?
+
+    unformattedFile=$(gofmt -l "$abs")
+    _set_fmt_error_code $unformattedFile
+    _check_error_code $?
+done <<< $files
+
+exit $error
